/* eslint-disable */
/**
 * Generated API for Convex
 *
 * THIS FILE IS GENERATED BY CONVEX. DO NOT EDIT.
 * To regenerate, run `npx convex dev` or `npx convex codegen`.
 */

// API structure matching our convex functions
export const api = {
  activities: {
    getRecentActivities: "activities:getRecentActivities" as any,
    getActivitiesByTimeRange: "activities:getActivitiesByTimeRange" as any,
    logActivity: "activities:logActivity" as any,
    logSystemActivity: "activities:logSystemActivity" as any,
    getActivityStats: "activities:getActivityStats" as any,
  },
  calendar: {
    getEventsByDateRange: "calendar:getEventsByDateRange" as any,
    getWeekEvents: "calendar:getWeekEvents" as any,
    createEvent: "calendar:createEvent" as any,
    updateEventStatus: "calendar:updateEventStatus" as any,
    getCronJobs: "calendar:getCronJobs" as any,
    importCronJobs: "calendar:importCronJobs" as any,
    getUpcomingEvents: "calendar:getUpcomingEvents" as any,
    deleteEvent: "calendar:deleteEvent" as any,
  },
  search: {
    search: "search:search" as any,
    addToIndex: "search:addToIndex" as any,
    getIndexedFiles: "search:getIndexedFiles" as any,
    getRecentIndexed: "search:getRecentIndexed" as any,
    clearFileIndex: "search:clearFileIndex" as any,
    searchWithContext: "search:searchWithContext" as any,
    getSearchStats: "search:getSearchStats" as any,
    reindexAll: "search:reindexAll" as any,
  },
  tasks: {
    getTasks: "tasks:getTasks" as any,
    getTask: "tasks:getTask" as any,
    createTask: "tasks:createTask" as any,
    updateTaskStatus: "tasks:updateTaskStatus" as any,
    updateTask: "tasks:updateTask" as any,
    deleteTask: "tasks:deleteTask" as any,
    getTasksByDueDate: "tasks:getTasksByDueDate" as any,
    getTaskStats: "tasks:getTaskStats" as any,
    getOverdueTasks: "tasks:getOverdueTasks" as any,
  },
};

export const internal = {};
export const components = {};
