/* eslint-disable */
/**
 * Generated API types for Convex.
 *
 * THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.
 */

import type { ApiFromModules } from "convex/server";
import type * as tasks from "../tasks.js";

/**
 * A type describing your app's public Convex API.
 *
 * This type includes information about which arguments each function expects and
 * what each function returns.
 */
export type API = ApiFromModules<{
  tasks: typeof tasks;
}>;

export declare const api: API;
export declare const internal: API;
