/* eslint-disable */
/**
 * Generated Data Model for Convex
 *
 * THIS FILE IS GENERATED BY CONVEX. DO NOT EDIT.
 * To regenerate, run `npx convex dev` or `npx convex codegen`.
 */

import type { GenericId } from "convex/values";

export type TableNames = string;
export type IndexNames = string;

export type Doc<T extends TableNames> = any;
export type Id<T extends TableNames = TableNames> = GenericId<T>;

export interface DataModel {
  [tableName: string]: {
    document: any;
    fieldPaths: string;
    indexes: any;
    searchIndexes: any;
  };
}
