/* eslint-disable */
/**
 * Generated server helpers for Convex.
 *
 * THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.
 */

import type {
  ActionBuilder,
  HttpActionBuilder,
  MutationBuilder,
  QueryBuilder,
} from "convex/server";
import type { DataModel } from "./dataModel.js";

export declare const query: QueryBuilder<DataModel, "public">;
export declare const mutation: MutationBuilder<DataModel, "public">;
export declare const action: ActionBuilder<DataModel, "public">;
export declare const httpAction: HttpActionBuilder;
