/* eslint-disable */
/**
 * Generated Server Functions for Convex
 *
 * THIS FILE IS GENERATED BY CONVEX. DO NOT EDIT.
 * To regenerate, run `npx convex dev` or `npx convex codegen`.
 */

import type { DataModel } from "./dataModel.js";

export interface QueryCtx {
  db: {
    query: (table: string) => any;
    get: (id: any) => Promise<any>;
    insert: (table: string, data: any) => Promise<any>;
    patch: (id: any, data: any) => Promise<void>;
    delete: (id: any) => Promise<void>;
  };
}

export interface MutationCtx extends QueryCtx {}
export interface ActionCtx extends QueryCtx {}

export const query = (fn: any) => fn;
export const mutation = (fn: any) => fn;
export const internalQuery = (fn: any) => fn;
export const internalMutation = (fn: any) => fn;
export const internalAction = (fn: any) => fn;
export const action = (fn: any) => fn;
export const httpAction = (fn: any) => fn;

export type DatabaseReader = any;
export type DatabaseWriter = any;
export type GenericActionCtx<DataModel> = ActionCtx;
export type GenericMutationCtx<DataModel> = MutationCtx;
export type GenericQueryCtx<DataModel> = QueryCtx;
